# Generated by Django 2.2 on 2020-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
