# Generated by Django 2.2 on 2019-12-20 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('type', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrugType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='INN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternationalName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PharmacotherapeuticGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrematureTermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('reason', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=50, null=True)),
                ('trade_name', models.CharField(max_length=3000, null=True)),
                ('drug_form', models.CharField(max_length=3000)),
                ('formula', models.TextField(null=True)),
                ('registration_number', models.CharField(max_length=30, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('expiration_date', models.CharField(max_length=20, null=True)),
                ('has_bio_origin', models.BooleanField(null=True)),
                ('has_phyto_origin', models.BooleanField(null=True)),
                ('is_orphan', models.BooleanField(null=True)),
                ('is_homeopatic', models.BooleanField(null=True)),
                ('instruction_url', models.TextField(null=True)),
                ('INN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.INN')),
                ('atcs', models.ManyToManyField(to='drugs.ATC')),
                ('drug_applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='firms.Applicant')),
                ('drug_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.DrugType')),
                ('international_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.InternationalName')),
                ('manufacturers', models.ManyToManyField(to='firms.Manufacturer')),
                ('marketing_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.MarketingStatus')),
                ('pharmacotherapeutic_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.PharmacotherapeuticGroup')),
                ('premature_termination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drugs.PrematureTermination')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
