# Generated by Django 2.2 on 2020-01-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ('trade_name',)},
        ),
        migrations.AlterField(
            model_name='drug',
            name='atcs',
            field=models.ManyToManyField(related_name='atcs_set', to='drugs.ATC'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='international_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_names', to='drugs.InternationalName'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='manufacturers',
            field=models.ManyToManyField(related_name='manufacturers_set', to='firms.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='marketing_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_status_set', to='drugs.MarketingStatus'),
        ),
    ]
