# Generated by Django 2.2 on 2020-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20200120_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drug_form',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drug',
            name='trade_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='internationalname',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='marketingstatus',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pharmacotherapeuticgroup',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
